# Generated by Django 6.0.6 on 2026-06-26 08:02

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('number_label', models.CharField(blank=True, max_length=20)),
                ('project_number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('title_break', models.CharField(blank=True, max_length=200)),
                ('role_label', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description_short', models.TextField(blank=True)),
                ('description_long', tinymce.models.HTMLField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('frame_variant', models.CharField(choices=[('MEDIMAP', 'MediMap'), ('GITHUB', 'GitHub'), ('AIRBNB', 'Airbnb'), ('ESCROW', 'Escrow'), ('TIMESHEET', 'Timesheet'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=12)),
                ('frame_tag', models.CharField(blank=True, max_length=80)),
                ('frame_subtitle', models.CharField(blank=True, max_length=200)),
                ('version_label', models.CharField(blank=True, max_length=20)),
                ('footer_left', models.CharField(blank=True, max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('live_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('case_study_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Gallery Image',
                'verbose_name_plural': 'Project Gallery Images',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('key', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=120)),
                ('position', models.CharField(choices=[('TOP_LEFT', 'Top Left'), ('TOP_RIGHT', 'Top Right')], default='TOP_LEFT', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_lines', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Meta',
                'verbose_name_plural': 'Project Meta',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('label', models.CharField(max_length=80)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Tag',
                'verbose_name_plural': 'Project Tags',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
