# Generated by Django 6.0.6 on 2026-06-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('number_label', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('title_break', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('stack_label', models.CharField(blank=True, max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
