# Generated by Django 6.0.6 on 2026-06-26 08:02

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Know me more.', max_length=200)),
                ('paragraph_1', tinymce.models.HTMLField(blank=True)),
                ('paragraph_2', tinymce.models.HTMLField(blank=True)),
                ('paragraph_cinematic_1', tinymce.models.HTMLField(blank=True)),
                ('paragraph_cinematic_2', tinymce.models.HTMLField(blank=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('message', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=255)),
                ('href', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('LOCATION', 'Location'), ('STATUS', 'Status'), ('SOCIAL', 'Social'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=10)),
                ('is_clickable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Channel',
                'verbose_name_plural': 'Contact Channels',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default="Let's get in touch.", max_length=200)),
                ('lead_text', models.TextField(blank=True)),
                ('body_text', tinymce.models.HTMLField(blank=True)),
                ('cinematic_lead', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Kaku', max_length=80)),
                ('last_name', models.CharField(default='Amsalu', max_length=80)),
                ('lede', tinymce.models.HTMLField(blank=True)),
                ('eyebrow_text', models.CharField(default='Portfolio / 2025 — Volume One', max_length=120)),
                ('role_strip_role', models.TextField(blank=True)),
                ('meta_status', models.CharField(blank=True, max_length=120)),
                ('meta_domain', models.CharField(blank=True, max_length=120)),
                ('meta_location', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Hero',
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('label', models.CharField(max_length=80)),
                ('anchor', models.CharField(blank=True, max_length=120)),
                ('external_url', models.URLField(blank=True)),
                ('target', models.CharField(choices=[('ONEPAGE', 'One Page'), ('CINEMATIC', 'Cinematic'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
            ],
            options={
                'verbose_name': 'Nav Link',
                'verbose_name_plural': 'Nav Links',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('twitter_handle', models.CharField(blank=True, max_length=80)),
                ('canonical_url', models.URLField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('owner_name', models.CharField(default='Kaku Amsalu', max_length=120)),
                ('owner_initials', models.CharField(default='K.A.', max_length=12)),
                ('portfolio_year', models.IntegerField(default=2025)),
                ('available_status', models.BooleanField(default=True)),
                ('available_label', models.CharField(default='Available 2025', max_length=80)),
                ('location_short', models.CharField(default='Addis Ababa · ET', max_length=120)),
                ('location_full', models.CharField(default='AAiT, Addis Ababa, ET', max_length=200)),
                ('timezone_label', models.CharField(default='EAT', max_length=20)),
                ('remote_friendly', models.BooleanField(default=True)),
                ('copyright_text', models.CharField(blank=True, max_length=200)),
                ('footer_quip', models.CharField(default='Crafted with passion, caffeine & spite.', max_length=200)),
                ('cinematic_url_label', models.CharField(default='Cinematic ↗', max_length=60)),
                ('onepage_url_label', models.CharField(default='One Page', max_length=60)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('platform', models.CharField(choices=[('GITHUB', 'GitHub'), ('LINKEDIN', 'LinkedIn'), ('TWITTER', 'Twitter'), ('DRIBBBLE', 'Dribbble'), ('BEHANCE', 'Behance'), ('EMAIL', 'Email')], max_length=12)),
                ('url', models.URLField()),
                ('display_label', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=255)),
                ('is_link', models.BooleanField(default=False)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='core.about')),
            ],
            options={
                'verbose_name': 'Fact',
                'verbose_name_plural': 'Facts',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('label', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.hero')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
