# Generated by Django 6.0.6 on 2026-06-26 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Skill Group',
                'verbose_name_plural': 'Skill Groups',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=120)),
                ('display_label', models.CharField(blank=True, max_length=120)),
                ('proficiency', models.IntegerField(default=3)),
                ('show_in_ticker', models.BooleanField(default=False)),
                ('ticker_row', models.CharField(choices=[('ROW_1', 'Row 1'), ('ROW_2', 'Row 2')], default='ROW_1', max_length=8)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.skillgroup')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
